In [27]:
import pandas as pd

In [28]:
#series 1d 1 col, dataframe 2d rxc

In [29]:
#series
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [30]:
di = {
    "name": ["aman", "rahul", "suman"],
    "age": [20, 21, 22]
}

df = pd.DataFrame(di)
df.head()

    name  age
0   aman   20
1  rahul   21
2  suman   22

In [31]:
#add col
marks = [90,80,70]
df.insert(1,"Marks",marks)
df.head()

    name  Marks  age
0   aman     90   20
1  rahul     80   21
2  suman     70   22

In [32]:
d1 = {
    "ID": [1, 2, 3],
    "subject": ["python", "java", "ai"]
}

df1 = pd.DataFrame(d1)

df1

   ID subject
0   1  python
1   2    java
2   3      ai

In [33]:
print(df.columns)
print(df1.columns)

Index(['name', 'Marks', 'age'], dtype='object')
Index(['ID', 'subject'], dtype='object')

In [34]:
print(df.head())
print(df1.head())

    name  Marks  age
0   aman     90   20
1  rahul     80   21
2  suman     70   22
   ID subject
0   1  python
1   2    java
2   3      ai

In [35]:
print(df)
print("\nColumns in df:", df.columns)

print("\n")
print(df1)
print("\nColumns in df1:", df1.columns)

    name  Marks  age
0   aman     90   20
1  rahul     80   21
2  suman     70   22

Columns in df: Index(['name', 'Marks', 'age'], dtype='object')


   ID subject
0   1  python
1   2    java
2   3      ai

Columns in df1: Index(['ID', 'subject'], dtype='object')

In [37]:
df["ID"] = [1, 2, 3]

print(df)

    name  Marks  age  ID
0   aman     90   20   1
1  rahul     80   21   2
2  suman     70   22   3

In [38]:
data = pd.merge(df, df1, on="ID", how="inner")
print(data)

    name  Marks  age  ID subject
0   aman     90   20   1  python
1  rahul     80   21   2    java
2  suman     70   22   3      ai

In [39]:
data.tail()

    name  Marks  age  ID subject
0   aman     90   20   1  python
1  rahul     80   21   2    java
2  suman     70   22   3      ai

In [44]:
import os

print(os.listdir("DATA"))

['matches.csv', 'tips-dataset.csv']

In [48]:
with open("DATA/tips-dataset.csv", "r", encoding="utf-8") as f:
    print(f.read(500))

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from pandas import Series, DataFrame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "df1=pd.read_csv('../input/tipping/tips.csv')"
   ]
  },
  {
   "cell_type": "code",
   "e

In [49]:
import os

print(os.path.getsize("DATA/tips-dataset.csv"))

734643

In [50]:
with open("DATA/tips-dataset.csv", "r", encoding="utf-8") as f:
    print(f.readline())

{

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   Marks   3 non-null      int64
 2   age     3 non-null      int64
 3   ID      3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

In [52]:
df.shape

(3, 4)

In [53]:
df.describe()

       Marks   age   ID
count    3.0   3.0  3.0
mean    80.0  21.0  2.0
std     10.0   1.0  1.0
min     70.0  20.0  1.0
25%     75.0  20.5  1.5
50%     80.0  21.0  2.0
75%     85.0  21.5  2.5
max     90.0  22.0  3.0

In [55]:
data.isnull().sum()

name       0
Marks      0
age        0
ID         0
subject    0
dtype: int64

In [63]:
url = "https://github.com/Urvity03/PBEL_batch_7/blob/main/DATA/tips-dataset.csv"

In [65]:
print(url)

https://github.com/Urvity03/PBEL_batch_7/blob/main/DATA/tips-dataset.csv

In [68]:
import requests

url = "https://raw.githubusercontent.com/Urvity03/PBEL_batch_7/main/DATA/tips-dataset.csv"

response = requests.get(url)

print(response.status_code)
print(response.text[:500])

200
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from pandas import Series, DataFrame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "df1=pd.read_csv('../input/tipping/tips.csv')"
   ]
  },
  {
   "cell_type": "code",
   "e